const COUNTRY_NAMES = {
  // English → ISO
  afghanistan: "AFG",
  albania: "ALB",
  algeria: "DZA",
  andorra: "AND",
  angola: "AGO",
  "antigua and barbuda": "ATG",
  argentina: "ARG",
  armenia: "ARM",
  australia: "AUS",
  austria: "AUT",
  azerbaijan: "AZE",
  bahamas: "BHS",
  bahrain: "BHR",
  bangladesh: "BGD",
  barbados: "BRB",
  belarus: "BLR",
  belgium: "BEL",
  belize: "BLZ",
  benin: "BEN",
  bhutan: "BTN",
  bolivia: "BOL",
  "bosnia and herzegovina": "BIH",
  bosnia: "BIH",
  botswana: "BWA",
  brazil: "BRA",
  brunei: "BRN",
  bulgaria: "BGR",
  "burkina faso": "BFA",
  burundi: "BDI",
  "cabo verde": "CPV",
  "cape verde": "CPV",
  cambodia: "KHM",
  cameroon: "CMR",
  canada: "CAN",
  "central african republic": "CAF",
  chad: "TCD",
  chile: "CHL",
  china: "CHN",
  colombia: "COL",
  comoros: "COM",
  congo: "COG",
  "costa rica": "CRI",
  "côte d'ivoire": "CIV",
  "cote d'ivoire": "CIV",
  "ivory coast": "CIV",
  croatia: "HRV",
  cuba: "CUB",
  cyprus: "CYP",
  "czech republic": "CZE",
  czechia: "CZE",
  "democratic republic of the congo": "COD",
  drc: "COD",
  denmark: "DNK",
  djibouti: "DJI",
  dominica: "DMA",
  "dominican republic": "DOM",
  ecuador: "ECU",
  egypt: "EGY",
  "el salvador": "SLV",
  "equatorial guinea": "GNQ",
  eritrea: "ERI",
  estonia: "EST",
  eswatini: "SWZ",
  swaziland: "SWZ",
  ethiopia: "ETH",
  fiji: "FJI",
  finland: "FIN",
  france: "FRA",
  gabon: "GAB",
  gambia: "GMB",
  georgia: "GEO",
  germany: "DEU",
  ghana: "GHA",
  greece: "GRC",
  grenada: "GRD",
  guatemala: "GTM",
  guinea: "GIN",
  "guinea-bissau": "GNB",
  guyana: "GUY",
  haiti: "HTI",
  honduras: "HND",
  hungary: "HUN",
  iceland: "ISL",
  india: "IND",
  indonesia: "IDN",
  iran: "IRN",
  iraq: "IRQ",
  ireland: "IRL",
  israel: "ISR",
  italy: "ITA",
  jamaica: "JAM",
  japan: "JPN",
  jordan: "JOR",
  kazakhstan: "KAZ",
  kenya: "KEN",
  kiribati: "KIR",
  kosovo: "XKX",
  kuwait: "KWT",
  kyrgyzstan: "KGZ",
  laos: "LAO",
  latvia: "LVA",
  lebanon: "LBN",
  lesotho: "LSO",
  liberia: "LBR",
  libya: "LBY",
  liechtenstein: "LIE",
  lithuania: "LTU",
  luxembourg: "LUX",
  madagascar: "MDG",
  malawi: "MWI",
  malaysia: "MYS",
  maldives: "MDV",
  mali: "MLI",
  malta: "MLT",
  "marshall islands": "MHL",
  mauritania: "MRT",
  mauritius: "MUS",
  mexico: "MEX",
  micronesia: "FSM",
  moldova: "MDA",
  monaco: "MCO",
  mongolia: "MNG",
  montenegro: "MNE",
  morocco: "MAR",
  mozambique: "MOZ",
  myanmar: "MMR",
  burma: "MMR",
  namibia: "NAM",
  nauru: "NRU",
  nepal: "NPL",
  netherlands: "NLD",
  holland: "NLD",
  "new zealand": "NZL",
  nicaragua: "NIC",
  niger: "NER",
  nigeria: "NGA",
  "north korea": "PRK",
  "north macedonia": "MKD",
  norway: "NOR",
  oman: "OMN",
  pakistan: "PAK",
  palau: "PLW",
  palestine: "PSE",
  panama: "PAN",
  "papua new guinea": "PNG",
  paraguay: "PRY",
  peru: "PER",
  philippines: "PHL",
  poland: "POL",
  portugal: "PRT",
  qatar: "QAT",
  romania: "ROU",
  russia: "RUS",
  rwanda: "RWA",
  "saint kitts and nevis": "KNA",
  "saint lucia": "LCA",
  "saint vincent and the grenadines": "VCT",
  samoa: "WSM",
  "san marino": "SMR",
  "sao tome and principe": "STP",
  "saudi arabia": "SAU",
  senegal: "SEN",
  serbia: "SRB",
  seychelles: "SYC",
  "sierra leone": "SLE",
  singapore: "SGP",
  slovakia: "SVK",
  slovenia: "SVN",
  "solomon islands": "SLB",
  somalia: "SOM",
  "south africa": "ZAF",
  "south korea": "KOR",
  korea: "KOR",
  "south sudan": "SSD",
  spain: "ESP",
  "sri lanka": "LKA",
  sudan: "SDN",
  suriname: "SUR",
  sweden: "SWE",
  switzerland: "CHE",
  syria: "SYR",
  taiwan: "TWN",
  tajikistan: "TJK",
  tanzania: "TZA",
  thailand: "THA",
  timorleste: "TLS",
  "east timor": "TLS",
  togo: "TGO",
  tonga: "TON",
  "trinidad and tobago": "TTO",
  tunisia: "TUN",
  turkey: "TUR",
  turkiye: "TUR",
  turkmenistan: "TKM",
  tuvalu: "TUV",
  uganda: "UGA",
  ukraine: "UKR",
  "united arab emirates": "ARE",
  uae: "ARE",
  "united kingdom": "GBR",
  uk: "GBR",
  britain: "GBR",
  england: "GBR",
  "united states": "USA",
  "united states of america": "USA",
  usa: "USA",
  uruguay: "URY",
  uzbekistan: "UZB",
  vanuatu: "VUT",
  "vatican city": "VAT",
  venezuela: "VEN",
  vietnam: "VNM",
  yemen: "YEM",
  zambia: "ZMB",
  zimbabwe: "ZWE",
  // Chinese → ISO
  阿富汗: "AFG",
  阿尔巴尼亚: "ALB",
  阿尔及利亚: "DZA",
  安道尔: "AND",
  安哥拉: "AGO",
  安提瓜和巴布达: "ATG",
  阿根廷: "ARG",
  亚美尼亚: "ARM",
  澳大利亚: "AUS",
  奥地利: "AUT",
  阿塞拜疆: "AZE",
  巴哈马: "BHS",
  巴林: "BHR",
  孟加拉国: "BGD",
  巴巴多斯: "BRB",
  白俄罗斯: "BLR",
  比利时: "BEL",
  伯利兹: "BLZ",
  贝宁: "BEN",
  不丹: "BTN",
  玻利维亚: "BOL",
  波斯尼亚: "BIH",
  波黑: "BIH",
  博茨瓦纳: "BWA",
  巴西: "BRA",
  文莱: "BRN",
  保加利亚: "BGR",
  布基纳法索: "BFA",
  布隆迪: "BDI",
  佛得角: "CPV",
  柬埔寨: "KHM",
  喀麦隆: "CMR",
  加拿大: "CAN",
  中非: "CAF",
  乍得: "TCD",
  智利: "CHL",
  中国: "CHN",
  哥伦比亚: "COL",
  科摩罗: "COM",
  刚果: "COG",
  哥斯达黎加: "CRI",
  科特迪瓦: "CIV",
  克罗地亚: "HRV",
  古巴: "CUB",
  塞浦路斯: "CYP",
  捷克: "CZE",
  丹麦: "DNK",
  吉布提: "DJI",
  多米尼克: "DMA",
  多米尼加: "DOM",
  厄瓜多尔: "ECU",
  埃及: "EGY",
  萨尔瓦多: "SLV",
  赤道几内亚: "GNQ",
  厄立特里亚: "ERI",
  爱沙尼亚: "EST",
  斯威士兰: "SWZ",
  埃塞俄比亚: "ETH",
  斐济: "FJI",
  芬兰: "FIN",
  法国: "FRA",
  加蓬: "GAB",
  冈比亚: "GMB",
  格鲁吉亚: "GEO",
  德国: "DEU",
  加纳: "GHA",
  希腊: "GRC",
  格林纳达: "GRD",
  危地马拉: "GTM",
  几内亚: "GIN",
  几内亚比绍: "GNB",
  圭亚那: "GUY",
  海地: "HTI",
  洪都拉斯: "HND",
  匈牙利: "HUN",
  冰岛: "ISL",
  印度: "IND",
  印度尼西亚: "IDN",
  伊朗: "IRN",
  伊拉克: "IRQ",
  爱尔兰: "IRL",
  以色列: "ISR",
  意大利: "ITA",
  牙买加: "JAM",
  日本: "JPN",
  约旦: "JOR",
  哈萨克斯坦: "KAZ",
  肯尼亚: "KEN",
  基里巴斯: "KIR",
  科索沃: "XKX",
  科威特: "KWT",
  吉尔吉斯斯坦: "KGZ",
  老挝: "LAO",
  拉脱维亚: "LVA",
  黎巴嫩: "LBN",
  莱索托: "LSO",
  利比里亚: "LBR",
  利比亚: "LBY",
  列支敦士登: "LIE",
  立陶宛: "LTU",
  卢森堡: "LUX",
  马达加斯加: "MDG",
  马拉维: "MWI",
  马来西亚: "MYS",
  马尔代夫: "MDV",
  马里: "MLI",
  马耳他: "MLT",
  马绍尔群岛: "MHL",
  毛里塔尼亚: "MRT",
  毛里求斯: "MUS",
  墨西哥: "MEX",
  密克罗尼西亚: "FSM",
  摩尔多瓦: "MDA",
  摩纳哥: "MCO",
  蒙古: "MNG",
  黑山: "MNE",
  摩洛哥: "MAR",
  莫桑比克: "MOZ",
  缅甸: "MMR",
  纳米比亚: "NAM",
  瑙鲁: "NRU",
  尼泊尔: "NPL",
  荷兰: "NLD",
  新西兰: "NZL",
  尼加拉瓜: "NIC",
  尼日尔: "NER",
  尼日利亚: "NGA",
  朝鲜: "PRK",
  北马其顿: "MKD",
  挪威: "NOR",
  阿曼: "OMN",
  巴基斯坦: "PAK",
  帕劳: "PLW",
  巴勒斯坦: "PSE",
  巴拿马: "PAN",
  巴布亚新几内亚: "PNG",
  巴拉圭: "PRY",
  秘鲁: "PER",
  菲律宾: "PHL",
  波兰: "POL",
  葡萄牙: "PRT",
  卡塔尔: "QAT",
  罗马尼亚: "ROU",
  俄罗斯: "RUS",
  卢旺达: "RWA",
  圣基茨和尼维斯: "KNA",
  圣卢西亚: "LCA",
  圣文森特: "VCT",
  萨摩亚: "WSM",
  圣马力诺: "SMR",
  圣多美和普林西比: "STP",
  沙特阿拉伯: "SAU",
  塞内加尔: "SEN",
  塞尔维亚: "SRB",
  塞舌尔: "SYC",
  塞拉利昂: "SLE",
  新加坡: "SGP",
  斯洛伐克: "SVK",
  斯洛文尼亚: "SVN",
  所罗门群岛: "SLB",
  索马里: "SOM",
  南非: "ZAF",
  韩国: "KOR",
  南苏丹: "SSD",
  西班牙: "ESP",
  斯里兰卡: "LKA",
  苏丹: "SDN",
  苏里南: "SUR",
  瑞典: "SWE",
  瑞士: "CHE",
  叙利亚: "SYR",
  台湾: "TWN",
  塔吉克斯坦: "TJK",
  坦桑尼亚: "TZA",
  泰国: "THA",
  东帝汶: "TLS",
  多哥: "TGO",
  汤加: "TON",
  特立尼达和多巴哥: "TTO",
  突尼斯: "TUN",
  土耳其: "TUR",
  土库曼斯坦: "TKM",
  图瓦卢: "TUV",
  乌干达: "UGA",
  乌克兰: "UKR",
  阿联酋: "ARE",
  英国: "GBR",
  美国: "USA",
  乌拉圭: "URY",
  乌兹别克斯坦: "UZB",
  瓦努阿图: "VUT",
  梵蒂冈: "VAT",
  委内瑞拉: "VEN",
  越南: "VNM",
  也门: "YEM",
  赞比亚: "ZMB",
  津巴布韦: "ZWE",
};

// ISO 3166-1 numeric → alpha-3. world-atlas/countries-110m.json uses numeric
// codes as the feature `id` (e.g. "392" for Japan), so the map must translate
// them to alpha-3 to line up with our country_counts keys.
const NUMERIC_TO_ALPHA3 = {
  "004": "AFG", "008": "ALB", "010": "ATA", "012": "DZA", "024": "AGO",
  "031": "AZE", "032": "ARG", "036": "AUS", "040": "AUT", "044": "BHS",
  "050": "BGD", "051": "ARM", "056": "BEL", "064": "BTN", "068": "BOL",
  "070": "BIH", "072": "BWA", "076": "BRA", "084": "BLZ", "090": "SLB",
  "096": "BRN", "100": "BGR", "104": "MMR", "108": "BDI", "112": "BLR",
  "116": "KHM", "120": "CMR", "124": "CAN", "140": "CAF", "144": "LKA",
  "148": "TCD", "152": "CHL", "156": "CHN", "158": "TWN", "170": "COL",
  "178": "COG", "180": "COD", "188": "CRI", "191": "HRV", "192": "CUB",
  "196": "CYP", "203": "CZE", "204": "BEN", "208": "DNK", "214": "DOM",
  "218": "ECU", "222": "SLV", "226": "GNQ", "231": "ETH", "232": "ERI",
  "233": "EST", "238": "FLK", "242": "FJI", "246": "FIN", "250": "FRA",
  "260": "ATF", "262": "DJI", "266": "GAB", "268": "GEO", "270": "GMB",
  "275": "PSE", "276": "DEU", "288": "GHA", "300": "GRC", "304": "GRL",
  "320": "GTM", "324": "GIN", "328": "GUY", "332": "HTI", "340": "HND",
  "348": "HUN", "352": "ISL", "356": "IND", "360": "IDN", "364": "IRN",
  "368": "IRQ", "372": "IRL", "376": "ISR", "380": "ITA", "384": "CIV",
  "388": "JAM", "392": "JPN", "398": "KAZ", "400": "JOR", "404": "KEN",
  "408": "PRK", "410": "KOR", "414": "KWT", "417": "KGZ", "418": "LAO",
  "422": "LBN", "426": "LSO", "428": "LVA", "430": "LBR", "434": "LBY",
  "440": "LTU", "442": "LUX", "450": "MDG", "454": "MWI", "458": "MYS",
  "466": "MLI", "478": "MRT", "484": "MEX", "496": "MNG", "498": "MDA",
  "499": "MNE", "504": "MAR", "508": "MOZ", "512": "OMN", "516": "NAM",
  "524": "NPL", "528": "NLD", "540": "NCL", "548": "VUT", "554": "NZL",
  "558": "NIC", "562": "NER", "566": "NGA", "578": "NOR", "586": "PAK",
  "591": "PAN", "598": "PNG", "600": "PRY", "604": "PER", "608": "PHL",
  "616": "POL", "620": "PRT", "624": "GNB", "626": "TLS", "630": "PRI",
  "634": "QAT", "642": "ROU", "643": "RUS", "646": "RWA", "682": "SAU",
  "686": "SEN", "688": "SRB", "694": "SLE", "703": "SVK", "704": "VNM",
  "705": "SVN", "706": "SOM", "710": "ZAF", "716": "ZWE", "724": "ESP",
  "728": "SSD", "729": "SDN", "732": "ESH", "740": "SUR", "748": "SWZ",
  "752": "SWE", "756": "CHE", "760": "SYR", "762": "TJK", "764": "THA",
  "768": "TGO", "780": "TTO", "784": "ARE", "788": "TUN", "792": "TUR",
  "795": "TKM", "800": "UGA", "804": "UKR", "807": "MKD", "818": "EGY",
  "826": "GBR", "834": "TZA", "840": "USA", "854": "BFA", "858": "URY",
  "860": "UZB", "862": "VEN", "887": "YEM", "894": "ZMB",
};

const ISO_CODE_REGEX = /^[A-Z]{3}$/;

// Convert a world-atlas feature id (ISO numeric, possibly null) plus an optional
// English name fallback into an ISO alpha-3 code. Returns null when unmatched.
export function numericToAlpha3(numericId, fallbackName) {
  if (numericId != null) {
    const padded = String(numericId).padStart(3, "0");
    if (NUMERIC_TO_ALPHA3[padded]) return NUMERIC_TO_ALPHA3[padded];
  }
  // Features with no numeric id (Kosovo, N. Cyprus, Somaliland): try by name.
  if (fallbackName) return lookupCountryCode(fallbackName);
  return null;
}

export function lookupCountryCode(name) {
  if (!name || typeof name !== "string") return null;
  const trimmed = name.trim();
  if (!trimmed) return null;

  // Already a valid ISO code
  const upper = trimmed.toUpperCase();
  if (ISO_CODE_REGEX.test(upper)) return upper;

  // Direct match (case-insensitive)
  const normalized = trimmed.toLowerCase();
  if (COUNTRY_NAMES[normalized]) return COUNTRY_NAMES[normalized];

  // Fuzzy: name contains a key or key contains name
  const key = Object.keys(COUNTRY_NAMES).find(
    (k) => normalized.includes(k) || k.includes(normalized)
  );
  if (key) return COUNTRY_NAMES[key];

  return null;
}

export function getAllCountryCodes() {
  const codes = new Set(Object.values(COUNTRY_NAMES));
  return [...codes].sort();
}

export function getCountryName(countryCode) {
  const upper = countryCode.toUpperCase();
  const entry = Object.entries(COUNTRY_NAMES).find(([, v]) => v === upper);
  return entry ? entry[0] : null;
}
