name: pgtap

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - "supabase/**"
      - "test/rls/**"
      - ".github/workflows/pgtap.yml"
  pull_request:

jobs:
  pgtap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: 2.98.2
      - run: supabase start
      - run: supabase db reset
      - run: supabase test db test/rls
